### PR TITLE
Fix Wallpapers, fix links, add new picture.

### PR DESCRIPTION
**Pull request by ariporad**
The title

### CODE REVIEW

**Comment by ablankenship10** [comment]
Dev footer doesn't link to the new sub

**Comment by ariporad** [comment]
The what footer?

**Comment by ablankenship10** [comment]
The footer on dev which should be the latest code. It looks like you only changed it in the header links.

**Comment by ariporad** [comment]
Fixed

**Comment by ablankenship10** [comment]
Looks good

**Pull request merged**
